POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWZlOGUyOTI4NDVhNTQzMjY5ZDMxYyIsInVzZXJuYW1lIjoiZmVybmFuZG9tZyIsImlhdCI6MTY3ODQ4MDQzM30.BA38Cl-HKOdfsjtWuOAT0FBqUCPvqd-NGbjYFaKxEKo

{
    "content": "nueva nota Utilizando el middleware del user extractor",
    "important": true
}